name: "dbt_eda_tools"
version: "1.4.0"

profile: "dbt_eda_tools_bq"

# model-paths: ["examples"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  +enabled: false
  +post-hook:
    - "{{ dbt_eda_tools.get_row_count() }}"
    - "{{ dbt_eda_tools.get_preview(20) }}"
  dbt_eda_tools:
    +materialized: view

on-run-end:
  - "{{ dbt_eda_tools.estimate_build_cost() }}"

data_tests:
  +enabled: false

vars:
  dbt_eda_tools_log_enable: false
