name: 'dbt_eda_tools'
version: '1.3.6'

profile: 'dbt_eda_tools_duck'

# model-paths: ["examples"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  +enabled: "{{ true if target.name == 'eda_dev' else false }}"
  +post-hook:
      - "{{ dbt_eda_tools.get_row_count() }}"
      - "{{ dbt_eda_tools.get_preview(20) }}"
  dbt_eda_tools:
    +materialized: view

data_tests:
  +enabled: "{{ true if target.name == 'eda_dev' else false }}"

vars:
  dbt_eda_tools_log_enable: "{{ true if target.name == 'eda_dev' else false }}"
