
name: 'dbt_eda_tools'
version: '0.1.0'

profile: 'dbt_eda_tools'

model-paths: ["examples"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.6.0", "<2.0.0"]

models:
  dbt_eda_tools:
    # Config indicated by + and applies to all files under models/example/
    +materialized: view

vars:
  variable_types :
    # assembled by integrating the types from
    # https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types and
    # https://docs.snowflake.com/en/sql-reference/data-types.html
    text: ('VARCHAR','CHAR', 'CHARACTER', 'STRING', 'TEXT')
    boolean: ('BOOLEAN','BOOL')
    date: ('DATE','DATETIME','TIMESTAMP','TIMESTAMP_LTZ','TIMESTAMP_NTZ','TIMESTAMP_TZ')
    numeric: ('NUMBER','DECIMAL','NUMERIC','INT','INTEGER','BIGINT','SMALLINT','FLOAT','FLOAT4','FLOAT8','DOUBLE','DOUBLE PRECISION','REAL','INT64', 'TINYINT','BYETEINT', 'BIGDECIMAL','FLOAT64')
    time: ('TIME')
    to_implement_binary: ('BINARY', 'VARBINARY')
    to_implement_semistructured: ('ARRAY', 'OBJECT', 'VARIANT')
    to_implement_geospatial: ('GEOGRAPHY','GEOMETRY')
    to_implement_vector: ('VECTOR')
